(require 'vemv.lang)
(require 'vemv.shortcuts.global.base)
(provide 'vemv.shortcuts.global)

(setq vemv/shortcuts/global/backspace               vemv/backspace
      vemv/shortcuts/global/down                    'next-line
      vemv/shortcuts/global/end                     'vemv/end-of-line-or-code
      vemv/shortcuts/global/f11                     'vemv/maximize
      vemv/shortcuts/global/f4                      vemv/f4
      vemv/shortcuts/global/f6                      'vemv/toggle-ns-hiding
      vemv/shortcuts/global/f7                      'vemv/previous-file-buffer
      vemv/shortcuts/global/f8                      'vemv/after-file-open
      vemv/shortcuts/global/f9                      'vemv/next-file-buffer
      vemv/shortcuts/global/home                    'back-to-indentation
      vemv/shortcuts/global/left                    'left-char
      vemv/shortcuts/global/primary-3               'vemv/indent
      vemv/shortcuts/global/primary-a               'vemv/copy-selection-or-next-sexpr
      vemv/shortcuts/global/primary-b               'vemv/duplicate
      vemv/shortcuts/global/primary-backspace       'vemv/delete-this-line
      vemv/shortcuts/global/primary-backtick        'other-frame
      vemv/shortcuts/global/primary-down            'forward-paragraph
      vemv/shortcuts/global/primary-equal           'mark-whole-buffer
      vemv/shortcuts/global/primary-f               vemv/c-f
      vemv/shortcuts/global/primary-j               vemv/c-j
      vemv/shortcuts/global/primary-k               'vemv/kill
      vemv/shortcuts/global/primary-n               vemv/c-n
      vemv/shortcuts/global/primary-o               'vemv/open
      vemv/shortcuts/global/primary-p               vemv/c-p
      vemv/shortcuts/global/primary-q               'save-buffers-kill-terminal
      vemv/shortcuts/global/primary-s               'vemv/save
      vemv/shortcuts/global/primary-S-z             'undo-tree-redo
      vemv/shortcuts/global/primary-semicolon       'toggle-truncate-lines
      vemv/shortcuts/global/primary-SPC             'cua-set-mark
      vemv/shortcuts/global/primary-t               'vemv/fiplr
      vemv/shortcuts/global/primary-up              'backward-paragraph
      vemv/shortcuts/global/primary-v               'cua-paste
      vemv/shortcuts/global/primary-w               'vemv/close-this
      vemv/shortcuts/global/primary-z               'undo-tree-undo
      vemv/shortcuts/global/RET                     'newline
      vemv/shortcuts/global/right                   'right-char
      vemv/shortcuts/global/S-backspace             vemv/shift-backspace
      vemv/shortcuts/global/secondary-a             vemv/alt-a
      vemv/shortcuts/global/secondary-backspace     'paredit-backward-kill-word
      vemv/shortcuts/global/secondary-colon         (argless (call-interactively 'eval-expression))
      vemv/shortcuts/global/secondary-k             vemv/alt-k
      vemv/shortcuts/global/secondary-left-bracket  'paredit-backward
      vemv/shortcuts/global/secondary-next          'previous-buffer
      vemv/shortcuts/global/secondary-prior         'next-buffer
      vemv/shortcuts/global/secondary-right-bracket 'paredit-forward
      vemv/shortcuts/global/secondary-S-k           vemv/alt-shift-k
      vemv/shortcuts/global/secondary-t             vemv/alt-t
      vemv/shortcuts/global/secondary-up            'paredit-splice-sexp-killing-backward
      vemv/shortcuts/global/secondary-x             'vemv/smex
      vemv/shortcuts/global/tertiary-backtick       'vemv/control-backtick
      vemv/shortcuts/global/tertiary-end            'end-of-buffer
      vemv/shortcuts/global/tertiary-home           'beginning-of-buffer
      vemv/shortcuts/global/tertiary-j              'cider-eval-sexp-at-point
      vemv/shortcuts/global/tertiary-k              'vemv/cut
      vemv/shortcuts/global/tertiary-o              'vemv/open-project
      vemv/shortcuts/global/tertiary-RET            'vemv/load-clojure-buffer
      vemv/shortcuts/global/up                      'previous-line)
