(require 'vemv.lang)
(require 'vemv.shortcuts.global.base)
(provide 'vemv.shortcuts.global)

(setq vemv/shortcuts/global/backspace               'vemv/backspace
      vemv/shortcuts/global/down                    'next-line
      vemv/shortcuts/global/end                     'vemv/end-of-line-or-code
      vemv/shortcuts/global/f11                     'vemv/maximize
      vemv/shortcuts/global/f4                      nil
      vemv/shortcuts/global/f6                      'vemv/toggle-ns-hiding
      vemv/shortcuts/global/f7                      'vemv/previous-file-buffer
      vemv/shortcuts/global/f8                      'vemv/after-file-open
      vemv/shortcuts/global/f9                      'vemv/next-file-buffer
      vemv/shortcuts/global/home                    'back-to-indentation
      vemv/shortcuts/global/left                    'left-char
      vemv/shortcuts/global/next                    'cua-scroll-up
      vemv/shortcuts/global/primary-1               'vemv/onelineize
      vemv/shortcuts/global/primary-3               'vemv/indent
      vemv/shortcuts/global/primary-6               'vemv/emacs-reload
      vemv/shortcuts/global/primary-8               'vemv/toggle-verbosity
      vemv/shortcuts/global/primary-a               'vemv/copy-selection-or-next-sexpr
      vemv/shortcuts/global/primary-b               'vemv/duplicate
      vemv/shortcuts/global/primary-backspace       'vemv/delete-this-line
      vemv/shortcuts/global/primary-backtick        'other-frame
      vemv/shortcuts/global/primary-down            'forward-paragraph
      vemv/shortcuts/global/primary-equal           'mark-whole-buffer
      vemv/shortcuts/global/primary-f               'vemv/search-in-this-buffer
      vemv/shortcuts/global/primary-j               'vemv/clojure-init-or-send-sexpr
      vemv/shortcuts/global/primary-k               'vemv/kill
      vemv/shortcuts/global/primary-n               'vemv/new-frame
      vemv/shortcuts/global/primary-o               'vemv/open
      vemv/shortcuts/global/primary-p               'vemv/repeat-last-search-in-this-buffer
      vemv/shortcuts/global/primary-q               'save-buffers-kill-terminal
      vemv/shortcuts/global/primary-r               'vemv/test-this-ns
      vemv/shortcuts/global/primary-s               'vemv/save
      vemv/shortcuts/global/primary-S-r             'vemv/run-this-deftest
      vemv/shortcuts/global/primary-S-z             'undo-tree-redo
      vemv/shortcuts/global/primary-semicolon       'toggle-truncate-lines
      vemv/shortcuts/global/primary-SPC             'cua-set-mark
      vemv/shortcuts/global/primary-t               'vemv/fiplr
      vemv/shortcuts/global/primary-u               'cljr-add-missing-libspec
      vemv/shortcuts/global/primary-up              'backward-paragraph
      vemv/shortcuts/global/primary-v               'vemv/paste-from-clipboard
      vemv/shortcuts/global/primary-w               'vemv/close-this
      vemv/shortcuts/global/primary-z               'undo-tree-undo
      vemv/shortcuts/global/prior                   'cua-scroll-down
      vemv/shortcuts/global/RET                     'newline-and-indent
      vemv/shortcuts/global/right                   'right-char
      vemv/shortcuts/global/S-backspace             'vemv/force-backspace
      vemv/shortcuts/global/secondary-a             'vemv/copy-sexpr-content-backward
      vemv/shortcuts/global/secondary-backspace     'paredit-backward-kill-word
      vemv/shortcuts/global/secondary-colon         (argless (call-interactively 'eval-expression))
      vemv/shortcuts/global/secondary-k             'vemv/kill-backward
      vemv/shortcuts/global/secondary-left-bracket  'paredit-backward
      vemv/shortcuts/global/secondary-next          'previous-buffer
      vemv/shortcuts/global/secondary-prior         'next-buffer
      vemv/shortcuts/global/secondary-right-bracket 'paredit-forward
      vemv/shortcuts/global/secondary-S-k           'vemv/kill-backward-copying-content
      vemv/shortcuts/global/secondary-t             'vemv/open-file-via-fiplr-then-close-previous-buffer
      vemv/shortcuts/global/secondary-up            'paredit-splice-sexp-killing-backward
      vemv/shortcuts/global/secondary-x             'vemv/smex
      vemv/shortcuts/global/tertiary-backtick       'vemv/jump-to-clojure-definition
      vemv/shortcuts/global/tertiary-left           'vemv/previous-project
      vemv/shortcuts/global/tertiary-right          'vemv/next-project
      vemv/shortcuts/global/tertiary-end            'end-of-buffer
      vemv/shortcuts/global/tertiary-home           'beginning-of-buffer
      vemv/shortcuts/global/tertiary-j              'cider-eval-sexp-at-point
      vemv/shortcuts/global/tertiary-k              'vemv/cut
      vemv/shortcuts/global/tertiary-o              'vemv/open-project
      vemv/shortcuts/global/tertiary-RET            'vemv/load-clojure-buffer
      vemv/shortcuts/global/tertiary-v              'vemv/paste-from-kill-list
      vemv/shortcuts/global/up                      'previous-line)

;; other S-RET syntaxes don't work. TODO: abstract away this
(global-set-key [(shift return)] 'vemv/clear-cider-repl-buffer)